# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=lcm_user
quarkus.datasource.password=lcm_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lcm_db

# quarkus.datasource.db-kind=h2
# quarkus.datasource.jdbc.url=jdbc:h2:mem:lcm_db;DB_CLOSE_DELAY=-1
# quarkus.datasource.username=sa
# quarkus.datasource.password=sa

# Hibernate
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# Timefold (OptaPlanner)
# Limit the solving time to 30 seconds for demo purposes
quarkus.timefold.solver.termination.spent-limit=30s

# HTTP
quarkus.http.port=8080
quarkus.http.access-log.enabled=true

# gRPC Configuration
quarkus.grpc.server.port=9000
quarkus.grpc.server.ssl.certificate=/home/wenbk/sc-scm/certs/server.pem
quarkus.grpc.server.ssl.key=/home/wenbk/sc-scm/certs/server-pkcs8.key
quarkus.grpc.server.ssl.trust-store=/home/wenbk/sc-scm/certs/truststore.jks
quarkus.grpc.server.ssl.trust-store-password=changeit
quarkus.grpc.server.ssl.client-auth=required
quarkus.grpc.server.ssl.trust-store-type=jks

# Redis
quarkus.redis.hosts=redis://localhost:6379

# Kafka
kafka.bootstrap.servers=localhost:9092

# Kafka Channels
# Outgoing: Scheduler -> JobQueue
mp.messaging.outgoing.job-queue-out.connector=smallrye-kafka
mp.messaging.outgoing.job-queue-out.topic=jobs.scheduled
mp.messaging.outgoing.job-queue-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Incoming: Dispatcher <- JobQueue
mp.messaging.incoming.job-queue-in.connector=smallrye-kafka
mp.messaging.incoming.job-queue-in.topic=jobs.scheduled
mp.messaging.incoming.job-queue-in.value.deserializer=com.sc.lcm.core.domain.JobDeserializer
mp.messaging.incoming.job-queue-in.group.id=lcm-core-group
mp.messaging.incoming.job-queue-in.auto.offset.reset=earliest

