{{- if and .Values.monitoring.alertmanager.enabled (eq .Values.monitoring.alertmanager.secrets.mode "chart-managed") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-alertmanager-secrets
  labels:
    {{- include "hyperscale-lcm.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-password: ""
  slack-webhook-url: ""
  pagerduty-routing-key: ""
{{- end }}
