{{- if and .Values.security.mtls.enabled .Values.security.mtls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.mtls.secretName }}
  labels:
    {{- include "hyperscale-lcm.labels" . | nindent 4 }}
type: Opaque
data:
  ca.pem: {{ required "security.mtls.secret.caPem is required when security.mtls.createSecret=true" .Values.security.mtls.secret.caPem | b64enc }}
  server.pem: {{ required "security.mtls.secret.serverPem is required when security.mtls.createSecret=true" .Values.security.mtls.secret.serverPem | b64enc }}
  server-pkcs8.key: {{ required "security.mtls.secret.serverPkcs8Key is required when security.mtls.createSecret=true" .Values.security.mtls.secret.serverPkcs8Key | b64enc }}
  client.pem: {{ required "security.mtls.secret.clientPem is required when security.mtls.createSecret=true" .Values.security.mtls.secret.clientPem | b64enc }}
  client.key: {{ required "security.mtls.secret.clientKey is required when security.mtls.createSecret=true" .Values.security.mtls.secret.clientKey | b64enc }}
  truststore.jks: {{ required "security.mtls.secret.truststoreJksBase64 is required when security.mtls.createSecret=true" .Values.security.mtls.secret.truststoreJksBase64 }}
  truststore-password: {{ required "security.mtls.secret.truststorePassword is required when security.mtls.createSecret=true" .Values.security.mtls.secret.truststorePassword | b64enc }}
{{- end }}
