// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/grpc/lcm.proto

package lcm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LcmService_RegisterSatellite_FullMethodName = "/lcm.LcmService/RegisterSatellite"
	LcmService_SendHeartbeat_FullMethodName     = "/lcm.LcmService/SendHeartbeat"
	LcmService_ReportDiscovery_FullMethodName   = "/lcm.LcmService/ReportDiscovery"
	LcmService_ConnectStream_FullMethodName     = "/lcm.LcmService/ConnectStream"
)

// LcmServiceClient is the client API for LcmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LcmServiceClient interface {
	// Satellite registers itself to the Core upon startup
	RegisterSatellite(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Periodic heartbeat to keep status online
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Report discovered assets (e.g. from network scan)
	ReportDiscovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	// Persistent bidirectional stream for command push
	ConnectStream(ctx context.Context, opts ...grpc.CallOption) (LcmService_ConnectStreamClient, error)
}

type lcmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLcmServiceClient(cc grpc.ClientConnInterface) LcmServiceClient {
	return &lcmServiceClient{cc}
}

func (c *lcmServiceClient) RegisterSatellite(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, LcmService_RegisterSatellite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lcmServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, LcmService_SendHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lcmServiceClient) ReportDiscovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, LcmService_ReportDiscovery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lcmServiceClient) ConnectStream(ctx context.Context, opts ...grpc.CallOption) (LcmService_ConnectStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LcmService_ServiceDesc.Streams[0], LcmService_ConnectStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lcmServiceConnectStreamClient{stream}
	return x, nil
}

type LcmService_ConnectStreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type lcmServiceConnectStreamClient struct {
	grpc.ClientStream
}

func (x *lcmServiceConnectStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lcmServiceConnectStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LcmServiceServer is the server API for LcmService service.
// All implementations must embed UnimplementedLcmServiceServer
// for forward compatibility
type LcmServiceServer interface {
	// Satellite registers itself to the Core upon startup
	RegisterSatellite(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Periodic heartbeat to keep status online
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Report discovered assets (e.g. from network scan)
	ReportDiscovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	// Persistent bidirectional stream for command push
	ConnectStream(LcmService_ConnectStreamServer) error
	mustEmbedUnimplementedLcmServiceServer()
}

// UnimplementedLcmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLcmServiceServer struct {
}

func (UnimplementedLcmServiceServer) RegisterSatellite(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSatellite not implemented")
}
func (UnimplementedLcmServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedLcmServiceServer) ReportDiscovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDiscovery not implemented")
}
func (UnimplementedLcmServiceServer) ConnectStream(LcmService_ConnectStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectStream not implemented")
}
func (UnimplementedLcmServiceServer) mustEmbedUnimplementedLcmServiceServer() {}

// UnsafeLcmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LcmServiceServer will
// result in compilation errors.
type UnsafeLcmServiceServer interface {
	mustEmbedUnimplementedLcmServiceServer()
}

func RegisterLcmServiceServer(s grpc.ServiceRegistrar, srv LcmServiceServer) {
	s.RegisterService(&LcmService_ServiceDesc, srv)
}

func _LcmService_RegisterSatellite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LcmServiceServer).RegisterSatellite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LcmService_RegisterSatellite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LcmServiceServer).RegisterSatellite(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LcmService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LcmServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LcmService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LcmServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LcmService_ReportDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LcmServiceServer).ReportDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LcmService_ReportDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LcmServiceServer).ReportDiscovery(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LcmService_ConnectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LcmServiceServer).ConnectStream(&lcmServiceConnectStreamServer{stream})
}

type LcmService_ConnectStreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type lcmServiceConnectStreamServer struct {
	grpc.ServerStream
}

func (x *lcmServiceConnectStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lcmServiceConnectStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LcmService_ServiceDesc is the grpc.ServiceDesc for LcmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LcmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.LcmService",
	HandlerType: (*LcmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSatellite",
			Handler:    _LcmService_RegisterSatellite_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _LcmService_SendHeartbeat_Handler,
		},
		{
			MethodName: "ReportDiscovery",
			Handler:    _LcmService_ReportDiscovery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectStream",
			Handler:       _LcmService_ConnectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpc/lcm.proto",
}
